#llama progrmas locales
a =("programa2")
b =("programa4")
c =("programa5")
d =("programa6")
f =("programa7")
g =("programa8")
h =("programa10")
i =("calculadora de descuento")
j =("positive and negative")
k =("notas de a a f")
l =("Triangulo")
m =("programa21")
n =("programa23")
o =("programa30")
p  =("programa31")
print (" fin del programa")