#programa 7.\n para calcular el volumen de un prisma rectangular\n")
i1 = input("Escriba el valor de largo")
i2 = input ("Escriba el valor de la Ancho")
i3 = input ("Escriba el valor de la Altura")
largo = float (il)
Ancho = float (i2)
Altura = float(i3)
vol = (Largo * Ancho * Altura )
volR = round(vol,4)
print("El volumen de un prisma rectangular:VOIR")
